/*
 * This source file was generated by the Gradle 'init' task
 */
package io.tamagotchi;

public class App {

    public static void main(String[] args) {
        io.tamagotchi.screens.MenuScreen.main(args);
    }
}
