name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.5.0
      with:
        wrapper-cache-enabled: true

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run tests with Gradle (includes Jacoco report generation)
      run: ./gradlew test

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jacoco-coverage-report
        path: app/build/reports/jacoco/test/html

    - name: Upload Test reports
      uses: actions/upload-artifact@v3.1.2
      with:
        name: test-reports
        path: app/build/reports/tests/test

    - name: Generate Javadoc with Gradle
      run: ./gradlew javadoc

    - name: Upload Javadoc Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          name: javadoc
          path: app/build/docs/javadoc
